apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cardlibrary-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: cardmarket
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cardlibrary
                port:
                  number: 8080